[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["openzeppelin=lib/openzeppelin-contracts", "erc721a=lib/ERC721A"]

# Ignore warning from lib
ignored_warnings_from = ["lib/"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
